baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'My New Hugo Site'
theme: 'kbdoc'

menu:
  main:
    - identifer: sakib
      name: sakib.dev
      url: https://sakib.dev
      weight: -110
